services:
  task-resources-proxy:
    image: nginx@sha256:3923f8de8d2214b9490e68fd6ae63ea604deddd166df2755b788bef04848b9bc
    pull_policy: never
    container_name: native-task-resources-prometheus-proxy
    restart: unless-stopped
    user: "101:101"
    read_only: true
    cap_drop: [ALL]
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:rw,nosuid,mode=1777,size=16m
      - /var/cache/nginx:rw,nosuid,mode=1777,size=16m
    ports:
      - "10.0.1.68:19090:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - grafana_monitor
networks:
  grafana_monitor:
    external: true
    name: services_grafana_monitor
