pid /tmp/nginx.pid;
error_log /dev/stderr crit;
events {}
http {
  log_format source_only '$remote_addr $request_method $uri $status';
  access_log /dev/stdout source_only;
  resolver 127.0.0.11 ipv6=off valid=10s;

  server {
    listen 8080;
    server_name _;

    location = /api/v1/query_range {
      if ($request_method != GET) { return 405; }
      allow 10.0.1.66;
      deny all;
      set $prometheus_origin "http://prometheus:9090";
      proxy_pass $prometheus_origin$request_uri;
      proxy_set_header Host prometheus:9090;
      proxy_connect_timeout 2s;
      proxy_read_timeout 10s;
    }

    location = /-/ready {
      if ($request_method != GET) { return 405; }
      allow 10.0.1.66;
      deny all;
      set $prometheus_origin "http://prometheus:9090";
      proxy_pass $prometheus_origin$request_uri;
      proxy_set_header Host prometheus:9090;
      proxy_connect_timeout 2s;
      proxy_read_timeout 10s;
    }

    location / { return 404; }
  }
}
