version: '3'

networks:
  traefik_monitor:
    external: true

services:
  prometheus:
    image: prom/prometheus
    user: "1000:1000"
    container_name: prometheus
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data:/prometheus
      - ./config:/etc/prometheus
    networks:
      - traefik_monitor
    command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--web.enable-admin-api'
        - '--web.enable-lifecycle'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/etc/prometheus/console_libraries'
        - '--web.console.templates=/etc/prometheus/consoles'