global:
  scrape_interval: 5s
  scrape_timeout: 1s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"
  - job_name: "node"
    static_configs:
      - targets:
          - "cvglcorevm.lan:9100"
          - "cvglsuppvm.lan:9100"
          - "login.cvgl.lab:9100"
          - "cvgl-node01.lan:9100"
          - "cvgl-node02.lan:9100"
          - "cvgl-node03.lan:9100"
          - "cvgl-node04.lan:9100"
          - "cvgl-node05.lan:9100"
          - "cvgl-node06.lan:9100"
          - "cvgl-node07.lan:9100"
          - "cvgl-node08.lan:9100"
  - job_name: "cadvisor"
    scrape_interval: 15s
    static_configs:
      - targets:
          - "cvglsuppvm.lan:9080"
          - "cvglloginnode.lan:9080"
          - "cvgl-node01.lan:9080"
          - "cvgl-node02.lan:9080"
          - "cvgl-node03.lan:9080"
          - "cvgl-node04.lan:9080"
          - "cvgl-node05.lan:9080"
          - "cvgl-node06.lan:9080"
          - "cvgl-node07.lan:9080"
          - "cvgl-node08.lan:9080"
  - job_name: "dcgm"
    honor_timestamps: true
    scrape_interval: 15s
    static_configs:
      - targets:
          - "cvgl-node01.lan:9400"
          - "cvgl-node02.lan:9400"
          - "cvgl-node03.lan:9400"
          - "cvgl-node04.lan:9400"
          - "cvgl-node05.lan:9400"
          - "cvgl-node06.lan:9400"
          - "cvgl-node07.lan:9400"
          - "cvgl-node08.lan:9400"
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    metric_relabel_configs:
    - source_labels: [id]
      separator: ;
      regex: /docker/(.*)
      target_label: container_runtime_id
      replacement: $1
      action: replace
    - source_labels: [__name__, UUID]
      separator: ;
      regex: DCGM.*;(.*)
      target_label: gpu_uuid
      replacement: $1
      action: replace
    http_sd_configs:
    - follow_redirects: true
      refresh_interval: 1m
      url: http://cvglcorevm.lan:8080/prom/det-http-sd-config
  - job_name: "v2ray"
    metrics_path: /scrape
    static_configs:
      - targets:
          - "xray-jp-osaka-bwh-exporter:9550"
          - "xray-us-west-racknerd-12tb-exporter:9550"
          - "xray-usca1-bwh-megaboxpro-2tb-exporter:9550"
          - "xray-usca5-bwh-sla-1tb-exporter:9550"
          - "xray-usca6-bwh-1tb-exporter:9550"
  - job_name: det-master
    honor_timestamps: true
    scrape_interval: 15s
    metrics_path: prom/det-state-metrics
    scheme: http
    follow_redirects: true
    metric_relabel_configs:
    - source_labels: [task_actor]
      separator: ;
      regex: /experiments/(.+)\/.*\/.*
      target_label: experiment_id
      replacement: $1
      action: replace
    static_configs:
    - targets:
      - cvglcorevm.lan:8080
    bearer_token: "v2.public.eyJpZCI6MjA4NDgsInVzZXJfaWQiOjEsImV4cGlyeSI6IjIwMjYtMDUtMTRUMDA6MDA6MDYuODQxMDg5MDA0WiIsImNyZWF0ZWRfYXQiOiIyMDI2LTA1LTA3VDAwOjAwOjA2Ljg0MTA4OTAwNFoiLCJ0b2tlbl90eXBlIjoiVVNFUl9TRVNTSU9OIiwicmV2b2tlZF9hdCI6bnVsbCwiZGVzY3JpcHRpb24iOm51bGwsIkluaGVyaXRlZENsYWltcyI6bnVsbH24exSykqxAFppYZpJ3pNgN8-EdRdraXghMmvfI2E9jZnAXD9R6N_ZJ98bGFwqv41brfOwtNBaN9lD3MuF_zJMD.bnVsbA"
