version: '3'

networks:
  grafana_monitor:
    external: true

services:
  jp-central:
    image: teddysun/xray
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    networks:
      - grafana_monitor
    ports:
      - 1089:1089
      - 8889:8889
    volumes: 
      - ./jp-central/config:/etc/xray
      - ./jp-central/log:/var/log/xray
    expose:
      - 10085

  us-west:
    image: teddysun/xray
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    networks:
      - grafana_monitor
    ports:
      - 20089:1089
      - 28889:8889
    volumes: 
      - ./us-west/config:/etc/xray
      - ./us-west/log:/var/log/xray
    expose:
      - 10086

  xray-jp-central-exporter:
    image: wi1dcard/v2ray-exporter:master
    container_name: xray-jp-central-exporter
    environment:
      TZ: Asia/Shanghai
    networks:
      - grafana_monitor
    restart: unless-stopped
    command: 'v2ray-exporter --v2ray-endpoint "jp-central:10085" --listen ":9550"'

  xray-us-west-exporter:
    image: wi1dcard/v2ray-exporter:master
    container_name: xray-us-west-exporter
    environment:
      TZ: Asia/Shanghai
    networks:
      - grafana_monitor
    restart: unless-stopped
    command: 'v2ray-exporter --v2ray-endpoint "us-west:10086" --listen ":9550"'