entryPoints = ["web"]

[entryPoints]
    [entryPoints.web]
    address = ":80" 

[api]
    dashboard   = true
    debug       = true

[log]
    level       = "DEBUG"
    filePath    = "/var/log/traefik/traefik.log"

[accessLog]
    filePath    = "/var/log/traefik/access.log"

[providers.docker]
    exposedByDefault = false

[docker]
