[Service]
Environment="HTTP_PROXY=http://192.168.233.8:59889"
Environment="HTTPS_PROXY=http://192.168.233.8:59889"
Environment="NO_PROXY=localhost,127.0.0.1,nvcr.io,aliyuncs.com,cvgl.lab,harbor.cvgl.lab,10.0.1.68,192.168.233.8"
