version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - /srv/nfs/var/nextcloud/var/lib/postgresql/data:/var/lib/postgresql/data
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - /srv/nfs/var/nextcloud/var/www/html:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
      - nextcloud.env
    depends_on:
      - db
      - redis

  nextcloud:
    image: nginx:alpine
    restart: always
    ports:
      - 8008:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /srv/nfs/var/nextcloud/var/www/html:/var/www/html:ro
    depends_on:
      - app
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_traefik
      traefik.http.routers.nextcloud.rule: Host(`pan.cvgl.lab`)
      traefik.http.routers.nextcloud.entrypoints: web

  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      -  /srv/nfs/var/nextcloud/var/www/html:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
