global:
  scrape_interval: 5s
  scrape_timeout: 5s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"
  - job_name: "node"
    static_configs:
      - targets:
          - "cvglsuppvm.lan:9100"
          - "cvglloginnode.lan:9100"
          - "cvgl-node01.lan:9100"
          - "cvgl-node02.lan:9100"
          - "cvgl-node03.lan:9100"
          - "cvgl-node04.lan:9100"
  - job_name: "cadvisor"
    scrape_interval: 15s
    static_configs:
      - targets:
          - "cvglsuppvm.lan:9080"
          - "cvglloginnode.lan:9080"
          - "cvgl-node01.lan:9080"
          - "cvgl-node02.lan:9080"
          - "cvgl-node03.lan:9080"
          - "cvgl-node04.lan:9080"
  - job_name: "v2ray"
    metrics_path: /scrape
    static_configs:
      - targets:
          - "xray-jp-central-exporter:9550"
          - "xray-us-west-exporter:9550"
