global:
  scrape_interval: 5s
  scrape_timeout: 5s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"
  - job_name: "node"
    static_configs:
      - targets:
          - "node-exporter:9100"
  - job_name: "v2ray"
    metrics_path: /scrape
    static_configs:
      - targets:
          - "xray-us-west-exporter:9550"
