mkdir /SSD
mkdir /datasets
mkdir /workspace
mkdir /workspace/lzzhao
mkdir /workspace/wangpeng
mkdir /workspace/mrj
mkdir /workspace/lyh
mkdir /workspace/lmy
mkdir /workspace/lzq
mkdir /workspace/zzj
mkdir /workspace/peter
mkdir /workspace/hj
mkdir /workspace/wujing
mkdir /workspace/wanpian
mkdir /workspace/cym
mkdir /workspace/xulu
mkdir /workspace/songwei
mkdir /workspace/lwp
mkdir /workspace/dcr
mkdir /workspace/wmz