mkdir /SSD
mkdir /SSD_home
mkdir /SSD_datasets
mkdir /SSD3
mkdir /SSD3_home
mkdir /SSD3_datasets
mkdir /UNSAFE_SSD4
mkdir /datasets
mkdir /workspace
mkdir /workspace/lzzhao
mkdir /workspace/wangpeng
mkdir /workspace/mrj
mkdir /workspace/lyh
mkdir /workspace/lmy
mkdir /workspace/lzq
mkdir /workspace/zzj
mkdir /workspace/peter
mkdir /workspace/hj
mkdir /workspace/wujing
mkdir /workspace/wanpian
mkdir /workspace/cym
mkdir /workspace/xulu
mkdir /workspace/songwei
mkdir /workspace/lwp
mkdir /workspace/dcr
mkdir /workspace/wmz
mkdir /workspace/liuxiang
mkdir /workspace/gcc
mkdir /workspace/wdx
mkdir /workspace/hxn
mkdir /workspace/cxh
mkdir /workspace/hzc
mkdir /workspace/lxh
mkdir /workspace/xuqi
mkdir /workspace/test1
mkdir /workspace/temp1
mkdir /workspace/sht
mkdir /workspace/ghq
mkdir /workspace/wanghan
mkdir /workspace/scy
mkdir /workspace/xyf
mkdir /workspace/lihao
mkdir /workspace/xjz
mkdir /workspace/xiangfeng
mkdir /workspace/zhenhua
mkdir /workspace/wangchi
mkdir /workspace/snc
mkdir /workspace/liyaohui
mkdir /workspace/lzh