{
 "title": "Cluster Realtime Hardware Utilization (cAdvisor (TBA) and dcgm-exporter)",
 "description": "GPU/CPU system metrics configured for clusters running Determined with cAdvisor and DCGM",
 "tags": [
  "prometheus",
  "system",
  "node-exporter",
  "GPU"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "tags", "label": "tags", "query": { "query": "label_values(label)" } },
   {
    "name": "resourcepool",
    "label": "resource-pool",
    "query": {
     "query": "label_values(det_resource_pool)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Allocation",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(count by (gpu) (DCGM_FI_DEV_GPU_UTIL{det_resource_pool=~\"$resourcepool\"} > 0) or vector(0)) / sum(count by (gpu) (DCGM_FI_DEV_GPU_UTIL{det_resource_pool=~\"$resourcepool\"})) * 100"
    }
   ]
  },
  {
   "title": "GPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "avg(avg(DCGM_FI_DEV_GPU_UTIL{det_resource_pool=~\"$resourcepool\"}) by (gpu))"
    }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "avg(avg(DCGM_FI_DEV_MEM_COPY_UTIL{det_resource_pool=~\"$resourcepool\"}) by (gpu))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{det_resource_pool=~\"$resourcepool\"}[$__rate_interval])) / sum(machine_cpu_cores) * 100"
    }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_limit_bytes{det_resource_pool=~\"$resourcepool\"} - container_fs_usage_bytes{det_resource_pool=~\"$resourcepool\"}) / sum(container_fs_limit_bytes{det_resource_pool=~\"$resourcepool\"}) * 100"
    }
   ]
  },
  {
   "title": "Active GPUs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(count by (gpu) (DCGM_FI_DEV_GPU_UTIL{det_resource_pool=~\"$resourcepool\"} > 0) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Allocation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(count by (gpu) (DCGM_FI_DEV_GPU_UTIL{det_resource_pool=~\"$resourcepool\"} > 0) or vector(0)) / sum(count by (gpu) (DCGM_FI_DEV_GPU_UTIL{det_resource_pool=~\"$resourcepool\"})) * 100",
     "legendFormat": "Cluster Allocation"
    }
   ]
  },
  {
   "title": "GPU / GPU Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(avg(DCGM_FI_DEV_GPU_UTIL{det_resource_pool=~\"$resourcepool\"}) by (gpu))",
     "legendFormat": "GPU Util"
    },
    {
     "expr": "avg by (label) (avg by (experiment_id) (avg by (allocation_id) (avg by (container_id) (\n(DCGM_FI_DEV_GPU_UTIL{det_resource_pool=~\"$resourcepool\"} / on (gpu_uuid) group_right det_gpu_uuid_container_id))\n/ on (container_id) group_right det_container_id_allocation_id\n)\n/ on (allocation_id) group_right det_allocation_id_task_id_task_actor)\n/ on (experiment_id) group_right det_experiment_id_label{label=~\"$tags\"}) ",
     "legendFormat": "GPU Util: {{label}}"
    },
    {
     "expr": "avg by (label) (avg by (experiment_id) (avg by (allocation_id) (avg by (container_id) (\n(DCGM_FI_DEV_MEM_COPY_UTIL{det_resource_pool=~\"$resourcepool\"} / on (gpu_uuid) group_right det_gpu_uuid_container_id))\n/ on (container_id) group_right det_container_id_allocation_id\n)\n/ on (allocation_id) group_right det_allocation_id_task_id_task_actor)\n/ on (experiment_id) group_right det_experiment_id_label{label=~\"$tags\"}) ",
     "legendFormat": "GPU Memory: {{label}}"
    },
    {
     "expr": "avg(avg(DCGM_FI_DEV_MEM_COPY_UTIL{det_resource_pool=~\"$resourcepool\"}) by (gpu))",
     "legendFormat": "GPU Memory"
    }
   ]
  },
  {
   "title": "CPU / Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{det_resource_pool=~\"$resourcepool\"}[$__rate_interval])) / sum(machine_cpu_cores) * 100",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum by (label) (sum by (allocation_id) ((sum by (container_runtime_id) (rate(container_cpu_usage_seconds_total{}[$__rate_interval]))\n/ on (container_runtime_id) group_right det_container_id_runtime_container_id)\n/ on (container_id) group_right det_container_id_allocation_id) \n/ on (allocation_id) group_right det_allocation_id_task_id_task_actor\n/ on (experiment_id) group_right det_experiment_id_label{label=~\"$tags\"})",
     "legendFormat": "CPU Usage: {{label}}"
    },
    {
     "expr": "sum(container_memory_usage_bytes{det_resource_pool=~\"$resourcepool\"}) / sum(machine_memory_bytes{det_resource_pool=~\"$resourcepool\"}) * 100",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(container_fs_limit_bytes{det_resource_pool=~\"$resourcepool\"} - container_fs_usage_bytes{det_resource_pool=~\"$resourcepool\"}) / sum(container_fs_limit_bytes{det_resource_pool=~\"$resourcepool\"}) * 100",
     "legendFormat": "Free Disk Space"
    }
   ]
  }
 ]
}